name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  http: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
